package com.cognibank.usermng.usermngspringmicroserviceapp.repository;

import com.cognibank.usermng.usermngspringmicroserviceapp.model.User;
import com.cognibank.usermng.usermngspringmicroserviceapp.model.UserDetails;
import com.cognibank.usermng.usermngspringmicroserviceapp.model.UserType;
import com.cognibank.usermng.usermngspringmicroserviceapp.service.UserServiceTest;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

@RunWith(SpringRunner.class)
@SpringBootTest
@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_CLASS)
public class UserRepositoryTest {
    @Autowired
    private UserRepository userRepository;

    @Test
    public void createNewUser() {
        User newUser = new User();
        List<UserDetails> detailsList = new ArrayList<>();
        detailsList.add(new UserDetails()
                .withUser(newUser)
                .withFieldName("FirstName")
                .withFieldValue("Foo"));
        detailsList.add(new UserDetails()
                .withUser(newUser)
                .withFieldName("LastName")
                .withFieldValue("Bar"));
        newUser.withType(UserType.Manager)
                .withUserName("foobar")
                .withPassword("test")
                .withUserDetails(detailsList)
                .withActive(true);

        newUser = userRepository.save(newUser);
        assertNotNull("User should have an autogenerated ID", newUser.getId());
    }

    @Test(expected = DataIntegrityViolationException.class)
    public void cannotCreateSameFieldMoreThanOnceForAUser() {
        User newUser = new User();
        List<UserDetails> detailsList = new ArrayList<>();
        detailsList.add(new UserDetails()
                .withUser(newUser)
                .withFieldName("FirstName")
                .withFieldValue("Fooa"));
        detailsList.add(new UserDetails()
                .withUser(newUser)
                .withFieldName("FirstName")
                .withFieldValue("Foob"));
        newUser.withType(UserType.Manager)
                .withUserName("foobar11")
                .withPassword("test")
                .withUserDetails(detailsList)
                .withActive(true);

        newUser = userRepository.save(newUser);
        assertNotNull("User should have an autogenerated ID", newUser.getId());
    }

    @Test(expected = DataIntegrityViolationException.class)
    public void userNameUniquenessTest() {
        User user1 = new User()
                .withUserName("alok")
                .withActive(true)
                .withType(UserType.User)
                .withPassword("1234qwer");
        User user2 = new User()
                .withUserName("alok")
                .withActive(true)
                .withType(UserType.Manager)
                .withPassword("1234qwer");
        userRepository.save(user1);
        userRepository.save(user2);
    }
}